mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#配置web服务器的端口号
server:
  port: 8080
  #servlet:
   # context-path: /myblog

#数据库连接信息
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: my-blog-datasource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myblog?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC

  servlet:
    multipart:

      max-request-size: 100MB  #最大支持max-file-size: 10MB   #最大支持文件大小请求大小
